### ISSUE TITLE
Novelpia  不工作

### ISSUE THREAD

**Issue by codemonkey4578** [KodzukiMio/syosetu-kakuyomu-novelup-alphapolis-novelpia-downloader#3]
例如，第1页可以正常下载第1集至第10集，但第11集至第20集不能下载。 我希望你能帮我修改一下这个。

**Comment by KodzukiMio** [comment]
付费章节(未付费)的下载不了,你下载的是哪本小说?请给我一下url,便于排查问题

**Comment by KodzukiMio** [comment]
AI Translate:
유료 챕터(미결제)는 다운로드할 수 없습니다. 어떤 소설을 다운로드하신 건가요? 문제 확인을 위해 URL을 알려주시면 감사하겠습니다.

**Comment by codemonkey4578** [comment]
https://novelpia.com/novel/14143
下载的是这本小说

**Comment by codemonkey4578** [comment]
那么，用这个程序即使加入了收费服务，也不能下载收费次数吗？

**Comment by KodzukiMio** [comment]
Paid chapters mean that you can download them after you pay, because the unpaid chapter plugin cannot request the original text. Also, I tested the novel https://novelpia.com/novel/14143 just now and there was no problem. The download may fail due to a poor network connection. Switch to the first page, then click download, wait, and please try again.

付费章节指的是当你付费后就能够下载,因为未付费的章节插件无法请求到原文,然后就是,刚才https://novelpia.com/novel/14143这本小说我测试是没有问题的,网络不好可能会下载失败,切换到第一页,然后点击下载,等待,请再尝试一次看看

아래는 AI 번역입니다:: 유료 챕터는 결제 후 다운로드할 수 있다는 뜻입니다. 미결제 챕터는 플러그인이 원문을 요청할 수 없기 때문입니다. 그리고 방금 https://novelpia.com/novel/14143 이 소설은 제가 테스트했을 때 문제가 없었습니다. 네트워크가 불안정하면 다운로드에 실패할 수 있습니다. 첫 페이지로 이동한 다음 다운로드를 클릭하고 기다려주세요. 다시 한번 시도해 보세요.

**Comment by KodzukiMio** [comment]
https://github.com/user-attachments/assets/0cd36d61-7ec5-495c-b783-3693181d6cb7

**Comment by KodzukiMio** [comment]
We can communicate in English, or if it's more convenient for you, feel free to use your native language. I think that will make our conversation flow better.

**Comment by KodzukiMio** [comment]
We can communicate in English, or if it's more convenient for you, feel free to use your native language. I think that will make our conversation flow better.

**Comment by codemonkey4578** [comment]
I see
The link I posted is 194 episodes in total and there are 20 episodes per page, of which only the first to tenth episodes are downloaded and the eleventh to twenty episodes are not.
I sent you a video. Even if I try to download it from page 1, I can only download 100 novels with 194 total episodes. Is it because this is not a jp site?
https://github.com/user-attachments/assets/dca7efba-e79f-4a9c-a4bc-aa3a8ed88c92

**Comment by codemonkey4578** [comment]
I see
The link I posted is 194 episodes in total and there are 20 episodes per page, of which only the first to tenth episodes are downloaded and the eleventh to twenty episodes are not.
I sent you a video. Even if I try to download it from page 1, I can only download 100 novels with 194 total episodes. Is it because this is not a jp site?

**Comment by codemonkey4578** [comment]
Hahaha I found a way to use vpn to slow down internet ping so I get it normally haha
Thank you for your answer. It must have been a problem with the internet in our country

**Comment by KodzukiMio** [comment]
Great! Enjoy reading!
